pipeline
{
 agent any
 stages
 {
 	stage('Build Application')
 	{
 		steps{
 				bat 'cd mule && mvn clean install'
 			}
 	}
 	stage('Deploy Application to Mulesoft CloudHub')
 	{
 		steps{
 				bat 'mvn package deploy -DmuleDeploy'
 			}
 	}
 }
}